#define MATRIX_SUCCESS 0
#define MATRIX_SUCCESS_MESSAGE "Success"

#define MATRIX_MEMORY_ERROR 1
#define MATRIX_MEMORY_ERROR_MESSAGE "Memory error"

#define MATRIX_INVALID_DIMENSIONS 2
#define MATRIX_INVALID_DIMENSIONS_MESSAGE "Invalid dimensions"

#define MATRIX_INDEX_OUT_OF_BOUNDS 3
#define MATRIX_INDEX_OUT_OF_BOUNDS_MESSAGE "Index out of bounds"

#define MATRIX_NULL_POINTER 4
#define MATRIX_NULL_POINTER_MESSAGE "Null pointer"

#define MATRIX_POWER_NEGATIVE_EXPONENT 5
#define MATRIX_POWER_NEGATIVE_EXPONENT_MESSAGE "Negative exponent"